### ISSUE TITLE
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory(   return window && document && document.all && !window.atob;)

### ISSUE THREAD

**Issue by sagarloona4180** [utatti/perfect-scrollbar#767]
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\Sagar\Documents\my-ngccrm\ngccrm-cli\src'
ERROR in webpack-internal:///./node_modules/style-loader/lib/addStyles.js:23
        return window && document && document.all && !window.atob;
        ^

ReferenceError: window is not defined
    at eval (webpack-internal:///./node_modules/style-loader/lib/addStyles.js:23:2)
    at eval (webpack-internal:///./node_modules/style-loader/lib/addStyles.js:12:46)
    at module.exports (webpack-internal:///./node_modules/style-loader/lib/addStyles.js:67:88)
    at eval (webpack-internal:///./node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:12:81)
    at Object../node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:71:1)
    at __webpack_require__ (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:20:30)
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:63:18
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:66:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)

my package.json 

  "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/jquery": "^3.2.11",
    "@types/moment": "^2.13.0",
    "angular2-loaders-css": "^1.0.9",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "install": "^0.10.1",
    "jquery": "^3.2.1",
    "jspdf": "^1.3.5",
    "jspdf-autotable": "^2.3.2",
    "jszip": "^3.1.4",
    "moment": "^2.18.1",
    "ng2-bs3-modal": "0.13.0",
    "ngx-bootstrap": "^2.0.3",
    "ngx-perfect-scrollbar": "^4.9.6",
    "ngx-popover": "0.0.16",
    "node-sass": "^4.7.2",
    "npm": "^5.5.1",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.0",
    "@angular/compiler-cli": "^4.3.2",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "dargs": "^5.1.0",
    "grunt": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-sass": "^1.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.4.0"
  }
}

**Comment by nickbullock** [comment]
got this error too
